### ISSUE TITLE
Plugin error: react-social-media-embed error: ERROR: Could not resolve "scriptjs"

### ISSUE THREAD

**Issue by 3200pro** [sanity-io/hydrogen-sanity-demo#10]
Just a heads up on something I ran into. I was deploying a hydrogen store on Vercel, and the following error came up:

`ERROR: Could not resolve "scriptjs"`

It looks like this is due to the twitter dependency within the `react-social-media-embed `dependency

Removing `Instagram.client.tsx` solved the error on my end however it would be nice to keep the Instagram module if possible.

**Comment by robinpyon** [comment]
Thanks for flagging this @3200pro – admittedly, `react-social-media-embed` is probably a little overkill for this demo, given that it's only rendering IG embeds. Would definitely be open to removing it entirely!

That said, one possible workaround is to import the instagram component directly, which should bypass the issue which appears to originate in `react-twitter-embed`, e.g,

```javascript
// src/components/modules/Instagram.client.tsx
import {InstagramEmbed} from 'react-social-media-embed/dist/components/embeds/InstagramEmbed';
...
```

Hope that helps!
