### ISSUE TITLE
Preview API route is not found on production (Oxygen)

### ISSUE THREAD

**Issue by Monolith-agency** [sanity-io/hydrogen-sanity-demo#100]
Hi, I was configuring the preview panels in Sanity Studio when I realized that my production app was missing the API routes.

I know the preview route `/api/preview` works on the dev server and does make it to the build (works with `shopify hydrogen preview`).

But when I deploy to Oxygen the route is `Not found`. 

Could it be that Oxygen doesn't handle those? Should I host somewhere else?

**Comment by thebiggianthead** [comment]
Oxygen can handle it - the route would return 404 if the environment variables to enable live preview aren't set - see [this line](https://github.com/sanity-io/hydrogen-sanity-demo/blob/4bfe59aa88cba9672c58319a4596737462158137/server.ts#L64) for where these are used in the the `server.ts` file.

**Comment by Monolith-agency** [comment]
Well... I was indeed simply missing an environment variable in Oxygen.

Thanks for the support.
