### ISSUE TITLE
Update to @shopify/hydrogen 2023.10.2

### ISSUE THREAD

**Issue by octave** [sanity-io/hydrogen-sanity-demo#104]
Do you have any plans to update it to the latest `@shopify/hydrogen` (`2023.10.2`)? I tried to just update the packages but it breaks at few different points.

**Comment by thebiggianthead** [comment]
Just pushed an update to bring up to date with latest hydrogen :-)

**Comment by octave** [comment]
@thebiggianthead Thank you so much!!
