### ISSUE TITLE
The `useSanityQuery` hook frequently fails during development

### ISSUE THREAD

**Issue by ramiroazar** [sanity-io/hydrogen-sanity-demo#11]
While developing using `yarn dev`, updates that trigger a `page reload` instead of a `hmr update` frequently render the `NotFound` component instead of the correct route components (ie. `Layout`, `HomeHero`, `ModuleGrid`, etc).

This seems to be caused by the `useSanityQuery` hook returning `undefined` around 50% of the time, which in turn renders the conditional `NotFound` component.

https://github.com/sanity-io/hydrogen-sanity-demo/blob/main/src/routes/index.server.tsx#L27

This is exacerbated by updates to server components always triggering a `page reload`.

Shopify/hydrogen#1824

Also by some other HMR issues in Hydrogen that cause a `page reload` during development fairly frequently.

Shopify/hydrogen#2096
Shopify/hydrogen#2092

This can be reproduced using this repository and following these steps.

1. Clone repository (e.g. `git clone git@github.com:sanity-io/hydrogen-sanity-demo.git`)
2. Install dependencies (e.g. `cd hydrogen-sanity-demo && yarn`)
3. Start development (e.g. `yarn dev`)
4. Open home page (e.g. `code ./src/routes/index.server.tsx`)
5. Save file (e.g. `command + S`)
6. Repeat the last step a few times and notice the `NotFound` component getting rendered

This is also happening with other Sanity projects, not just the example one used in this repo.

It only seems to happen during development, not builds, as seen in the hosted demo of this repo.

Does anyone know what would cause such inconsistent behaviour from the `useSanityQuery` hook?

**Comment by robinpyon** [comment]
Hey @ramiroazar, unfortunately I'm unable to repro this issue with the steps provided. 

`useSanityQuery` is a very thin wrapper around Hydrogen's `useQuery` hook that fetches from your Sanity dataset using the `@sanity/client` library. 

The fact that this is happening across other projects indicates to me that the issue might lie with `@sanity/client` – though it'd be good to dig deeper. Are you able to provide a reference to another project – or ideally a minimal example – where you're also coming across this issue?

**Comment by ramiroazar** [comment]
Thanks for having a look, @robinpyon.

I had another crack at this and identified a few more things worth noting.

When `data` in `useSanityQuery` is `undefined`, the hook itself returns the following.

```
error: Error: read ECONNRESET
at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -54,
    code: 'ECONNRESET',
    syscall: 'read'
}
```

This led me to the suggestion below, which I can confirm works.

https://stackoverflow.com/a/54306640

There does seem to be some kind of issue here, so here's a bunch of stuff I noticed in the process.

I can’t replicate anything similar within client components (ie. `*.client.tsx`) using the Sanity client directly, awaiting the exact same request (e.g. `await client.fetch(HOMEPAGE_CONTENT_QUERY)`) always returns a response.

I also can’t replicate within the actual `useSanityQuery.ts` file, as in awaiting the same request that is passed to the `useQuery` hook actually always returns a response, even after the `useSanityQuery` hook itself returns the above error instead, for literally the same request.

I also can’t replicate this using the same `useSanityQuery` hook with other APIs, swapping the Sanity client with a basic fetch to other APIs always returns a response, never the error above.

I also noticed that this doesn't happen on a Linux (`Manjaro 21.3.6`) machine, but it does on an Apple machine (`macOS Monterey 12.3.1`)

Interestingly, reducing the payload of the query makes `useSanityQuery` return a response more reliably, but that’s obviously not a viable option.

Different caching configurations (e.g. `CacheNone`, `devCache`, etc) don’t seem to have any effect.

Neither does changing the query key to something simpler.

All of this suggests there's something strange going on between the Sanity client and the `useQuery` hook, probably related to the size or the time of the request or the response.

Do you know of any potential issues with using the following in `useSanityQuery.ts` to work around this?

```
async () => await client.fetch(query, params, {
    headers: {
        Connection: 'keep-alive'
    }
})
```

**Comment by robinpyon** [comment]
Thank you for the excellent write up @ramiroazar

Quoting a colleague who is much closer to this than I am –

> The bug in this case seems to be a race condition that occurs due to these circumstances:
> - `get-it`, the main dependency of `@sanity/client`, has a lot of pending dependency updates that will address bugs in environments like nodejs running in macOS
> - whilst nodejs on Linux and in CJS environments is thoroughly tested, the hydrogen and oxygen env is still novel and not well tested.
> - It’s likely that the issue will resolve itself once we’re done updating `get-it`’s dependencies as part of its glow-up that started as part of the ESM effort for the client.

I think the above explains why this issue may be occurring for you in server and not client components. As I believe this issue is specific to `@sanity/client` and not hydrogen or other aspects of this demo, I'm going to close this issue for now.

However for completeness – if you're able to let me know which version of `@sanity/client` and node you're running locally, I'd be happy to continue trying to repro this.

Re: the usage of the connection header, I'm unsure of any side-effects – but given that this is an issue that affects you locally I'd suggest only adding that header in development.

**Comment by ramiroazar** [comment]
Thank you, @robinpyon, that does explain it.

I forgot to share these details.

`node@16` and `node@18`
`@sanity/client@3.3.2` and `@sanity/client@3.4.2`

I'll follow your suggestion and only add the header during develpment.

Should I be opening an issue in `@sanity/client` in the meantime?

Also wondering if you think it's worth mentioning this in the `README` or updating `useSanityQuery` to prevent other macOS users running into this?
