### ISSUE TITLE
Multiline groq queries not working on Oxygen

### ISSUE THREAD

**Issue by DanielHirunrusme** [sanity-io/hydrogen-sanity-demo#16]
I cloned this repo locally and deployed on Oxygen.

Locally, everything works as expected. On Oxygen, after much trial and error, I discovered:

1. Groq queries using groq`` do not work. I have to remove the groq method when passing the string
2. Multline queries do not work. Never experienced this before on other hosting like Vercel so perhaps an Oxygen-specific issue. 
3. Fragments do not work, unless they are all single-line...related to point 2

This is the query that finally works on Oxygen below. It's just the HOME_QUERY without line breaks. However, this is not really a solution as multiline should work ideally.

`const QUERY = `*[_type == 'home'][0]{ modules[] { _key, _type, (_type == "module.accordion") => { groups[] { _key, body[] { ..., markDefs[] { ..., (_type == 'annotationLinkExternal') => { _key, _type, newWindow, title, url, }, (_type == 'annotationLinkInternal') => { _key, _type, title, ...reference-> { "documentType": _type, (_type == "collection") => { "slug": "/collections/" + store.slug.current, }, (_type == "home") => { "slug": "/", }, (_type == "page") => { "slug": "/pages/" + slug.current, }, (_type == "product" && store.isEnabled && store.status == "active") => { "slug": "/products/" + store.slug.current, }, } }, (_type == 'annotationProduct') => { linkAction, productWithVariant { ... product->{ _id, "available": !store.isDeleted && store.status == 'active', "gid": store.gid, "slug": store.slug.current, "variantGid": coalesce(^.variant->store.gid, store.variants[0]->store.gid) } }, (linkAction != 'link') => { quantity } }, } }, title, } }, (_type == "module.callout") => { "link": links[0] { (_type == 'linkExternal') => { _key, _type, newWindow, title, url, }, (_type == 'linkInternal') => { _key, _type, title, ...reference-> { "documentType": _type, (_type == "collection") => { "slug": "/collections/" + store.slug.current, }, (_type == "home") => { "slug": "/", }, (_type == "page") => { "slug": "/pages/" + slug.current, }, (_type == "product" && store.isEnabled && store.status == "active") => { "slug": "/products/" + store.slug.current, }, } }, }, text }, (_type == 'module.callToAction') => { body, content[0] { _type, (_type == 'image') => { ..., "altText": asset->altText, "blurDataURL": asset->metadata.lqip, 'height': asset->metadata.dimensions.height, 'url': asset->url, 'width': asset->metadata.dimensions.width, }, (_type == 'productWithVariant') => { ... product->{ _id, "available": !store.isDeleted && store.status == 'active', "gid": store.gid, "slug": store.slug.current, "variantGid": coalesce(^.variant->store.gid, store.variants[0]->store.gid) } }, }, layout, "link": links[0] { (_type == 'linkExternal') => { _key, _type, newWindow, title, url, }, (_type == 'linkInternal') => { _key, _type, title, ...reference-> { "documentType": _type, (_type == "collection") => { "slug": "/collections/" + store.slug.current, }, (_type == "home") => { "slug": "/", }, (_type == "page") => { "slug": "/pages/" + slug.current, }, (_type == "product" && store.isEnabled && store.status == "active") => { "slug": "/products/" + store.slug.current, }, } }, }, title, }, (_type == "module.collection") => { collection->{ _id, colorTheme->{ 'background': background.hex, 'text': text.hex, }, "gid": store.gid, "slug": "/collections/" + store.slug.current, "title": store.title, "vector": vector.asset->url, }, showBackground }, (_type == "module.image") => { image { ..., "altText": asset->altText, "blurDataURL": asset->metadata.lqip, 'height': asset->metadata.dimensions.height, 'url': asset->url, 'width': asset->metadata.dimensions.width, }, (variant == 'callToAction') => { callToAction { "link": links[0] { (_type == 'linkExternal') => { _key, _type, newWindow, title, url, }, (_type == 'linkInternal') => { _key, _type, title, ...reference-> { "documentType": _type, (_type == "collection") => { "slug": "/collections/" + store.slug.current, }, (_type == "home") => { "slug": "/", }, (_type == "page") => { "slug": "/pages/" + slug.current, }, (_type == "product" && store.isEnabled && store.status == "active") => { "slug": "/products/" + store.slug.current, }, } }, }, title, } }, (variant == 'caption') => { caption, }, (variant == 'productHotspots') => { productHotspots[] { _key, _key, "product": productWithVariant { ... product->{ _id, "available": !store.isDeleted && store.status == 'active', "gid": store.gid, "slug": store.slug.current, "variantGid": coalesce(^.variant->store.gid, store.variants[0]->store.gid) } }, x, y } }, (variant == 'productTags') => { productTags[] { _key, ... product->{ _id, "available": !store.isDeleted && store.status == 'active', "gid": store.gid, "slug": store.slug.current, "variantGid": coalesce(^.variant->store.gid, store.variants[0]->store.gid) } }, }, variant, }, (_type == "module.instagram") => { url }, (_type == "module.product") => { productWithVariant { ... product->{ _id, "available": !store.isDeleted && store.status == 'active', "gid": store.gid, "slug": store.slug.current, "variantGid": coalesce(^.variant->store.gid, store.variants[0]->store.gid) } } }, }, "seo": { "description": seo.description, "image": seo.image { ..., "altText": asset->altText, "blurDataURL": asset->metadata.lqip, 'height': asset->metadata.dimensions.height, 'url': asset->url, 'width': asset->metadata.dimensions.width, }, "title": coalesce(seo.title, title), } }`;
`
Any thoughts here?

**Comment by pmkhoa** [comment]
It's crazy how much time I spent to debug this. This is a real pain.
