### ISSUE TITLE
Does this comply with the GDPR?

### ISSUE THREAD

**Issue by carstensbix** [sanity-io/hydrogen-sanity-demo#18]
I can't see any cookie bar for accepting cookies, does this imply the site doesn't have any cookies then?
If its not implemented any idea how it could be implemented?

**Comment by TimoSutterer** [comment]
It's currently not implemented. You could show a modal to new users and only set `hasUserConsent` to `true` (in `/app/root`) once the user gives consent.

**Comment by thebiggianthead** [comment]
This isn't implemented as regulations vary depending on location. As @TimoSutterer said, a modal and setting `hasUserContent` seems to be a sensible approach to me.
