### ISSUE TITLE
Seo from @shopify/hydrogen

### ISSUE THREAD

**Issue by benitodotcool** [sanity-io/hydrogen-sanity-demo#22]
Hey,

I'm at the end of a project I'm working on and I want to tackle SEO. I understand that this template uses the Seo component from `@shopify/hydrogen` combined with a custom `<DefaultSeo />` component. However, when I try to use `@shopify/hydrogen`'s Seo component, I always get `undefined` everywhere.

It seems that it comes from your template because when I use the [opengraph.xyz](https://www.opengraph.xyz/url/https%3A%2F%2Fhydrogen-sanity-demo.com%2F) or [socialsharepreview.com](https://socialsharepreview.com/?url=https://hydrogen-sanity-demo.com/) tool on any page of the demo, I also have `undefined` everywhere. 

Can you take a look at it?

Thank you!

benitodotcool

**Comment by benitodotcool** [comment]
Still ro results 😵‍💫

**Comment by thebiggianthead** [comment]
Hey @benitodotcool - do you have a more full code example showing the issue you're seeing here? Thanks!

**Comment by benitodotcool** [comment]
@thebiggianthead I've also tried to completely remove the `<DefaultSeo />` and the `<Seo />` and only work width the <Head /> lise so:
```html
<Head>
    <title>{sanityHome.seo.title} | onestar press</title>
    <meta name="description" content={sanityHome.seo.description} />
    <meta property="og:title" content={sanityHome.seo.title + ' | onestar press'} />
    <meta property="og:description" content={sanityHome.seo.description} />
    <meta property="og:image" content={sanityHome?.seo?.image?.url} />
    <meta name="twitter:title" content={sanityHome.seo.title + ' | onestar press'} />
    <meta name="twitter:description" content={sanityHome.seo.description} />
    <meta name="twitter:image" content={sanityHome?.seo?.image?.url} />
 </Head>
``` 

Again, the HTML render correctly, but nothing through the social share.

**Comment by thebiggianthead** [comment]
When visiting the site with the `?_bot` URL parameter, I'm seeing duplicate `<html>` tags in the source code: view-source:https://frontend-onestar-press.vercel.app/products/les-adieux?_bot

This suggests there might be something unusual going on in the source code which is causing duplicate tags, which might explain why you're seeing them as undefined.

**Comment by benitodotcool** [comment]
I've just updated the code to only have a `<Head />` inside [handle].server.tsx (`/products`):
Here is my `<Head />`:
```html
      <Head>
        <title>{sanityProduct.artist?.name ? `${sanityProduct.artist.name} | ${storefrontProduct.title}` : storefrontProduct.title}</title>
        <meta name="description" content={sanitySeo.description} />
        <meta property="og:type" content="og:product" />
        <meta property="og:title" content={sanityProduct.artist?.name ? `${sanityProduct.artist.name} | ${storefrontProduct.title}` : storefrontProduct.title} />
        <meta property="og:description" content={sanitySeo.description} />
        <meta property="og:image" content={storefrontProduct?.images?.edges[0].node?.url} />
        <meta name="twitter:title" content={sanityProduct.artist?.name ? `${sanityProduct.artist.name} | ${storefrontProduct.title}` : storefrontProduct.title} />
        <meta name="twitter:description" content={sanitySeo.description} />
        <meta name="twitter:image" content={storefrontProduct?.images?.edges[0].node?.url} />
      </Head>
```
No duplicated tags now, even with the suffix `?_bot`

**Comment by benitodotcool** [comment]
Hi!
This is how I managed to solve the problem:
I had a client component that had an error about windows.innerHeight, and this bug that only appeared on the client side broke the metadata preview!
