### ISSUE TITLE
Not working with Shopify Hydrogen v2.0

### ISSUE THREAD

**Issue by carstensbix** [sanity-io/hydrogen-sanity-demo#23]
Will this get updated to support the new major release of shopify hydrogen v2.0?

Or should people update it manually? 

Thanks in advance :)

**Comment by abdulrauf11** [comment]
What are some things we need to do if we were to update it manually?

**Comment by carstensbix** [comment]
If anyone decides to manually update, i would really appreciate it if you post the github link here to help everyone out :)

**Comment by carstensbix** [comment]
I am also interested in helping migrating to the new version. Write a message here then we can collaborate and update it together.

**Comment by tomdijss** [comment]
I'm also interested in updating to hydrogen v2 let me know how I can help.

**Comment by carstensbix** [comment]
Hey @tomdijss, what is your discord?

**Comment by tomdijss** [comment]
it is Tom Dijsselbloem#7424 @carstensbix

**Comment by HatimDa** [comment]
Did anyone got it working guys? what errors are you facing?

**Comment by carstensbix** [comment]
@HatimDa wanna help us?

**Comment by Draykee** [comment]
@carstensbix @tomdijss any fork or separate project yet?

**Comment by thebiggianthead** [comment]
We've just updated the repo with a new version of the demo built on Hydrogen with Remix.
