### ISSUE TITLE
Issue with hosting on hydrogen. 

### ISSUE THREAD

**Issue by hitpixel** [sanity-io/hydrogen-sanity-demo#30]
So after duplicating this github,

Changing the required code "storefront domains and keys" and connecting to hydrogen, the storefront shows nothing like page is not found, but the logo and footer shows? why is this happening, anyone having same issue?

Any help is much appreciated. 

Best Regards

**Comment by hitpixel** [comment]
It is asking to merge pull, how would i do this correctly?

I am actually not sure on what to do for this part?

![image](https://user-images.githubusercontent.com/59998304/232982075-0116e90a-3ea2-4d29-aafd-87890c9dde8f.png)


What do I have to do on this conflict

![image](https://user-images.githubusercontent.com/59998304/232982336-2744a921-7293-4e63-bc92-681c4bbf28bb.png)


again thanks for the help

**Comment by thebiggianthead** [comment]
@hitpixel Oxygen requires a Github workflow file to make deployments - see https://shopify.dev/docs/custom-storefronts/oxygen/storefronts#how-it-works

You'll need to resolve the conflict and merge the PR that Shopify creates in order for the deployment to complete. In terms of the merge conflicts, it's likely that the version from `main` is the correct version to keep here.
