### ISSUE TITLE
Search component

### ISSUE THREAD

**Issue by Moucky** [sanity-io/hydrogen-sanity-demo#69]
Hi all, I was wondering if anyone would be able to advise me on the best way to create a site search from the header. The search would need to query Sanity data and Shopify data. The complication may be that it is not a search route but a component. Any advice on the best way to approach this would be appreciated!

**Comment by Moucky** [comment]
I should add that I have attempted this by replicating the way the demo got collection data from components. I added a search query in utils.ts:

```
export const getSearchData = async ({context}: {context: AppLoadContext;}) => {
  const searchData: any = await context.sanity.query<any>({
    query: SEARCH,
  });
  const products: any = await context.storefront.query<any>(SEARCH_QUERY);

  return {
    products,
    searchData,
  };
};
```

and then resolved on the route:
```
const storefrontData = await getStorefrontData({page, context});
  const searchData = await getSearchData({context});
```

and finally accessed on the component:
```
  const [root] = useMatches();
  const {sanityDataset, sanityProjectID} = root.data;

  const [params] = useSearchParams()
  const searchTerm = params.get("q")
  const data = useMatches().find((match) => match.data?.searchData)?.data?.searchData || {};

  if (!searchTerm) {
    return null;
  }
  
  const results = data.searchData?.filter((data) => data?.title.toLowerCase().includes(searchTerm?.toLowerCase()));

  const groupBy = (array, key) => {
    return array.reduce((result, currentValue) => {
      (result[currentValue[key]] = result[currentValue[key]] || []).push(
        currentValue
      );
      return result;
    }, {});
  };

  const grouped = groupBy(results, '_type');

  const storefrontResults = data.products.products.nodes?.filter((data) => data?.title.toLowerCase().includes(searchTerm?.toLowerCase()));
```

I see the way the storefrontData is queried has been updated now and as I plan to update this also I will have to change my search. Any suggestions on the best way to do this? I don't think my current solution is the best.

**Comment by thebiggianthead** [comment]
Sorry for the delay in response here. I'll close this issue as stale given the time delay here, but do feel free to re-open.
