### ISSUE TITLE
Get Started

### ISSUE THREAD

**Issue by mtvchannel** [sanity-io/hydrogen-sanity-demo#78]
Hello,

I wanted to know how I can get Demo Content like not the products but the pages used in the demo in Sanity. I currently always get "**Page not found**" in my local environment.

Would be great if you could provide some documentation.

**Comment by FilipLjubic** [comment]
You add them in your sanity dashboard (https://github.com/sanity-io/sanity-shopify-studio) and link them up under 'settings' to either the menu links or footer

**Comment by viniciusgrando** [comment]
Hi!

I have the same question and I came across this Issue. I went to the Settings section and linked a page, which resulted in its display in the menu. However, the homepage is still showing the 404 error.

I did manage to customize the 404 error page, and it's working correctly, but it still appears as default when the site opens. The question is how can I add components, like a main hero banner and product sections, to this page like the demo?
